# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83d8d3d3b3948daebeba10d89421e043364124e40a7d5b99d04a42e014b647eb7d10cd71a41ea194a78dcd9276f57722f1cc2ba59675f0b57b6e96c78e4c9be1

test:
  secret_key_base: 6fc3fb6304c6bb5d26ccaac45556f5a37b287fb73435fe1664dfe6ca881808f83fa04cca755eb4e49d742013b16ad311d8f98b99643ba68d844ddd729b665b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
